### ISSUE TITLE
inline_test.cpp #41

### ISSUE THREAD

**Issue by wmamrak** [sabel83/metatest#1]
Hello,

the following line produces:

> error C2976: 'remove_parentheses_helper': too few template arguments
> error C2955: 'remove_parentheses_helper': use of class template requires template argument list

You can see the same behavior trying the following excerpt here: http://webcompiler.cloudapp.net/

``` c++
template<class T>
struct remove_parentheses_helper
{ typedef T type; };

template<class T>
struct remove_parentheses_helper<void (T)>
{ typedef T type; };

#define REMOVE_PARENTHESES(t) \
    remove_parentheses_helper<void (t)>::type

int main() {
    REMOVE_PARENTHESES(int);
    REMOVE_PARENTHESES((int));
}
```

**Comment by sabel83** [comment]
Hi, what are you trying to do?

**Comment by wmamrak** [comment]
Build the generated solution, as mentioned here: http://abel.web.elte.hu/metatest/build.html

**Comment by sabel83** [comment]
I think I've found (and fixed) the problem. Please try again.

**Comment by wmamrak** [comment]
Ok now, thanks.

**Comment by sabel83** [comment]
Thank you for the bug report.
